/* This file was generated by SableCC (http://www.sablecc.org/). */

package parser;

import node.*;
import analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 0;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 1;
    }

    @Override
    public void caseTLParen(@SuppressWarnings("unused") TLParen node)
    {
        this.index = 2;
    }

    @Override
    public void caseTRParen(@SuppressWarnings("unused") TRParen node)
    {
        this.index = 3;
    }

    @Override
    public void caseTLBrack(@SuppressWarnings("unused") TLBrack node)
    {
        this.index = 4;
    }

    @Override
    public void caseTRBrack(@SuppressWarnings("unused") TRBrack node)
    {
        this.index = 5;
    }

    @Override
    public void caseTLCurly(@SuppressWarnings("unused") TLCurly node)
    {
        this.index = 6;
    }

    @Override
    public void caseTRCurly(@SuppressWarnings("unused") TRCurly node)
    {
        this.index = 7;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 8;
    }

    @Override
    public void caseTNewScope(@SuppressWarnings("unused") TNewScope node)
    {
        this.index = 9;
    }

    @Override
    public void caseTEndScope(@SuppressWarnings("unused") TEndScope node)
    {
        this.index = 10;
    }

    @Override
    public void caseTLookup1(@SuppressWarnings("unused") TLookup1 node)
    {
        this.index = 11;
    }

    @Override
    public void caseTLookup2(@SuppressWarnings("unused") TLookup2 node)
    {
        this.index = 12;
    }

    @Override
    public void caseTBoolean(@SuppressWarnings("unused") TBoolean node)
    {
        this.index = 13;
    }

    @Override
    public void caseTChar(@SuppressWarnings("unused") TChar node)
    {
        this.index = 14;
    }

    @Override
    public void caseTFloat(@SuppressWarnings("unused") TFloat node)
    {
        this.index = 15;
    }

    @Override
    public void caseTInt(@SuppressWarnings("unused") TInt node)
    {
        this.index = 16;
    }

    @Override
    public void caseTVoid(@SuppressWarnings("unused") TVoid node)
    {
        this.index = 17;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 18;
    }

    @Override
    public void caseTKclass(@SuppressWarnings("unused") TKclass node)
    {
        this.index = 19;
    }

    @Override
    public void caseTMethod(@SuppressWarnings("unused") TMethod node)
    {
        this.index = 20;
    }

    @Override
    public void caseTVariable(@SuppressWarnings("unused") TVariable node)
    {
        this.index = 21;
    }

    @Override
    public void caseTNewBlock(@SuppressWarnings("unused") TNewBlock node)
    {
        this.index = 22;
    }

    @Override
    public void caseTEnclosingMethod(@SuppressWarnings("unused") TEnclosingMethod node)
    {
        this.index = 23;
    }

    @Override
    public void caseTPrintSymtab(@SuppressWarnings("unused") TPrintSymtab node)
    {
        this.index = 24;
    }

    @Override
    public void caseTIdent(@SuppressWarnings("unused") TIdent node)
    {
        this.index = 25;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 26;
    }
}
