/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAndExpr extends PAndExpr
{
    private PAndExpr _andExpr_;
    private TAnd _and_;
    private PEqualityExpr _equalityExpr_;

    public AAndExpr()
    {
        // Constructor
    }

    public AAndExpr(
        @SuppressWarnings("hiding") PAndExpr _andExpr_,
        @SuppressWarnings("hiding") TAnd _and_,
        @SuppressWarnings("hiding") PEqualityExpr _equalityExpr_)
    {
        // Constructor
        setAndExpr(_andExpr_);

        setAnd(_and_);

        setEqualityExpr(_equalityExpr_);

    }

    @Override
    public Object clone()
    {
        return new AAndExpr(
            cloneNode(this._andExpr_),
            cloneNode(this._and_),
            cloneNode(this._equalityExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndExpr(this);
    }

    public PAndExpr getAndExpr()
    {
        return this._andExpr_;
    }

    public void setAndExpr(PAndExpr node)
    {
        if(this._andExpr_ != null)
        {
            this._andExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._andExpr_ = node;
    }

    public TAnd getAnd()
    {
        return this._and_;
    }

    public void setAnd(TAnd node)
    {
        if(this._and_ != null)
        {
            this._and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._and_ = node;
    }

    public PEqualityExpr getEqualityExpr()
    {
        return this._equalityExpr_;
    }

    public void setEqualityExpr(PEqualityExpr node)
    {
        if(this._equalityExpr_ != null)
        {
            this._equalityExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalityExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._andExpr_)
            + toString(this._and_)
            + toString(this._equalityExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._andExpr_ == child)
        {
            this._andExpr_ = null;
            return;
        }

        if(this._and_ == child)
        {
            this._and_ = null;
            return;
        }

        if(this._equalityExpr_ == child)
        {
            this._equalityExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._andExpr_ == oldChild)
        {
            setAndExpr((PAndExpr) newChild);
            return;
        }

        if(this._and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        if(this._equalityExpr_ == oldChild)
        {
            setEqualityExpr((PEqualityExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
