/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACharLiteralPrimary extends PPrimary
{
    private TCharLiteral _charLiteral_;

    public ACharLiteralPrimary()
    {
        // Constructor
    }

    public ACharLiteralPrimary(
        @SuppressWarnings("hiding") TCharLiteral _charLiteral_)
    {
        // Constructor
        setCharLiteral(_charLiteral_);

    }

    @Override
    public Object clone()
    {
        return new ACharLiteralPrimary(
            cloneNode(this._charLiteral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACharLiteralPrimary(this);
    }

    public TCharLiteral getCharLiteral()
    {
        return this._charLiteral_;
    }

    public void setCharLiteral(TCharLiteral node)
    {
        if(this._charLiteral_ != null)
        {
            this._charLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._charLiteral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._charLiteral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._charLiteral_ == child)
        {
            this._charLiteral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._charLiteral_ == oldChild)
        {
            setCharLiteral((TCharLiteral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
