/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AClassHdr extends PClassHdr
{
    private TKclass _kclass_;
    private TIdentifier _identifier_;

    public AClassHdr()
    {
        // Constructor
    }

    public AClassHdr(
        @SuppressWarnings("hiding") TKclass _kclass_,
        @SuppressWarnings("hiding") TIdentifier _identifier_)
    {
        // Constructor
        setKclass(_kclass_);

        setIdentifier(_identifier_);

    }

    @Override
    public Object clone()
    {
        return new AClassHdr(
            cloneNode(this._kclass_),
            cloneNode(this._identifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClassHdr(this);
    }

    public TKclass getKclass()
    {
        return this._kclass_;
    }

    public void setKclass(TKclass node)
    {
        if(this._kclass_ != null)
        {
            this._kclass_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kclass_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kclass_)
            + toString(this._identifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kclass_ == child)
        {
            this._kclass_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kclass_ == oldChild)
        {
            setKclass((TKclass) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
