/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEndScopeCommand extends PCommand
{
    private TEndScope _endScope_;
    private TSemicolon _semicolon_;

    public AEndScopeCommand()
    {
        // Constructor
    }

    public AEndScopeCommand(
        @SuppressWarnings("hiding") TEndScope _endScope_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setEndScope(_endScope_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AEndScopeCommand(
            cloneNode(this._endScope_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEndScopeCommand(this);
    }

    public TEndScope getEndScope()
    {
        return this._endScope_;
    }

    public void setEndScope(TEndScope node)
    {
        if(this._endScope_ != null)
        {
            this._endScope_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._endScope_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._endScope_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._endScope_ == child)
        {
            this._endScope_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._endScope_ == oldChild)
        {
            setEndScope((TEndScope) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
