/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AFloatLiteralPrimary extends PPrimary
{
    private TFloatLit _floatLit_;

    public AFloatLiteralPrimary()
    {
        // Constructor
    }

    public AFloatLiteralPrimary(
        @SuppressWarnings("hiding") TFloatLit _floatLit_)
    {
        // Constructor
        setFloatLit(_floatLit_);

    }

    @Override
    public Object clone()
    {
        return new AFloatLiteralPrimary(
            cloneNode(this._floatLit_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFloatLiteralPrimary(this);
    }

    public TFloatLit getFloatLit()
    {
        return this._floatLit_;
    }

    public void setFloatLit(TFloatLit node)
    {
        if(this._floatLit_ != null)
        {
            this._floatLit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._floatLit_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._floatLit_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._floatLit_ == child)
        {
            this._floatLit_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._floatLit_ == oldChild)
        {
            setFloatLit((TFloatLit) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
