/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AIfElseMatched extends PMatched
{
    private TIf _if_;
    private PCondition _condition_;
    private PMatched _matchedIfThen_;
    private TElse _else_;
    private PMatched _matchedIfElse_;

    public AIfElseMatched()
    {
        // Constructor
    }

    public AIfElseMatched(
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") PCondition _condition_,
        @SuppressWarnings("hiding") PMatched _matchedIfThen_,
        @SuppressWarnings("hiding") TElse _else_,
        @SuppressWarnings("hiding") PMatched _matchedIfElse_)
    {
        // Constructor
        setIf(_if_);

        setCondition(_condition_);

        setMatchedIfThen(_matchedIfThen_);

        setElse(_else_);

        setMatchedIfElse(_matchedIfElse_);

    }

    @Override
    public Object clone()
    {
        return new AIfElseMatched(
            cloneNode(this._if_),
            cloneNode(this._condition_),
            cloneNode(this._matchedIfThen_),
            cloneNode(this._else_),
            cloneNode(this._matchedIfElse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfElseMatched(this);
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public PCondition getCondition()
    {
        return this._condition_;
    }

    public void setCondition(PCondition node)
    {
        if(this._condition_ != null)
        {
            this._condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condition_ = node;
    }

    public PMatched getMatchedIfThen()
    {
        return this._matchedIfThen_;
    }

    public void setMatchedIfThen(PMatched node)
    {
        if(this._matchedIfThen_ != null)
        {
            this._matchedIfThen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._matchedIfThen_ = node;
    }

    public TElse getElse()
    {
        return this._else_;
    }

    public void setElse(TElse node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    public PMatched getMatchedIfElse()
    {
        return this._matchedIfElse_;
    }

    public void setMatchedIfElse(PMatched node)
    {
        if(this._matchedIfElse_ != null)
        {
            this._matchedIfElse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._matchedIfElse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._condition_)
            + toString(this._matchedIfThen_)
            + toString(this._else_)
            + toString(this._matchedIfElse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._condition_ == child)
        {
            this._condition_ = null;
            return;
        }

        if(this._matchedIfThen_ == child)
        {
            this._matchedIfThen_ = null;
            return;
        }

        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        if(this._matchedIfElse_ == child)
        {
            this._matchedIfElse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._condition_ == oldChild)
        {
            setCondition((PCondition) newChild);
            return;
        }

        if(this._matchedIfThen_ == oldChild)
        {
            setMatchedIfThen((PMatched) newChild);
            return;
        }

        if(this._else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        if(this._matchedIfElse_ == oldChild)
        {
            setMatchedIfElse((PMatched) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
