/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AIfUnmatched extends PUnmatched
{
    private TIf _if_;
    private PCondition _condition_;
    private PGenericStmt _genericStmt_;

    public AIfUnmatched()
    {
        // Constructor
    }

    public AIfUnmatched(
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") PCondition _condition_,
        @SuppressWarnings("hiding") PGenericStmt _genericStmt_)
    {
        // Constructor
        setIf(_if_);

        setCondition(_condition_);

        setGenericStmt(_genericStmt_);

    }

    @Override
    public Object clone()
    {
        return new AIfUnmatched(
            cloneNode(this._if_),
            cloneNode(this._condition_),
            cloneNode(this._genericStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfUnmatched(this);
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public PCondition getCondition()
    {
        return this._condition_;
    }

    public void setCondition(PCondition node)
    {
        if(this._condition_ != null)
        {
            this._condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condition_ = node;
    }

    public PGenericStmt getGenericStmt()
    {
        return this._genericStmt_;
    }

    public void setGenericStmt(PGenericStmt node)
    {
        if(this._genericStmt_ != null)
        {
            this._genericStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._genericStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._condition_)
            + toString(this._genericStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._condition_ == child)
        {
            this._condition_ = null;
            return;
        }

        if(this._genericStmt_ == child)
        {
            this._genericStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._condition_ == oldChild)
        {
            setCondition((PCondition) newChild);
            return;
        }

        if(this._genericStmt_ == oldChild)
        {
            setGenericStmt((PGenericStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
