/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ALessThanOrEqComparisonExpr extends PComparisonExpr
{
    private PArithExpr _plusMinusSrc_;
    private TLessThanOrEq _lessThanOrEq_;
    private PArithExpr _plusMinusTarget_;

    public ALessThanOrEqComparisonExpr()
    {
        // Constructor
    }

    public ALessThanOrEqComparisonExpr(
        @SuppressWarnings("hiding") PArithExpr _plusMinusSrc_,
        @SuppressWarnings("hiding") TLessThanOrEq _lessThanOrEq_,
        @SuppressWarnings("hiding") PArithExpr _plusMinusTarget_)
    {
        // Constructor
        setPlusMinusSrc(_plusMinusSrc_);

        setLessThanOrEq(_lessThanOrEq_);

        setPlusMinusTarget(_plusMinusTarget_);

    }

    @Override
    public Object clone()
    {
        return new ALessThanOrEqComparisonExpr(
            cloneNode(this._plusMinusSrc_),
            cloneNode(this._lessThanOrEq_),
            cloneNode(this._plusMinusTarget_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessThanOrEqComparisonExpr(this);
    }

    public PArithExpr getPlusMinusSrc()
    {
        return this._plusMinusSrc_;
    }

    public void setPlusMinusSrc(PArithExpr node)
    {
        if(this._plusMinusSrc_ != null)
        {
            this._plusMinusSrc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusMinusSrc_ = node;
    }

    public TLessThanOrEq getLessThanOrEq()
    {
        return this._lessThanOrEq_;
    }

    public void setLessThanOrEq(TLessThanOrEq node)
    {
        if(this._lessThanOrEq_ != null)
        {
            this._lessThanOrEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lessThanOrEq_ = node;
    }

    public PArithExpr getPlusMinusTarget()
    {
        return this._plusMinusTarget_;
    }

    public void setPlusMinusTarget(PArithExpr node)
    {
        if(this._plusMinusTarget_ != null)
        {
            this._plusMinusTarget_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusMinusTarget_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plusMinusSrc_)
            + toString(this._lessThanOrEq_)
            + toString(this._plusMinusTarget_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plusMinusSrc_ == child)
        {
            this._plusMinusSrc_ = null;
            return;
        }

        if(this._lessThanOrEq_ == child)
        {
            this._lessThanOrEq_ = null;
            return;
        }

        if(this._plusMinusTarget_ == child)
        {
            this._plusMinusTarget_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plusMinusSrc_ == oldChild)
        {
            setPlusMinusSrc((PArithExpr) newChild);
            return;
        }

        if(this._lessThanOrEq_ == oldChild)
        {
            setLessThanOrEq((TLessThanOrEq) newChild);
            return;
        }

        if(this._plusMinusTarget_ == oldChild)
        {
            setPlusMinusTarget((PArithExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
