/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMethodScopeCommand extends PCommand
{
    private TEnclosingMethod _enclosingMethod_;
    private TSemicolon _semicolon_;

    public AMethodScopeCommand()
    {
        // Constructor
    }

    public AMethodScopeCommand(
        @SuppressWarnings("hiding") TEnclosingMethod _enclosingMethod_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setEnclosingMethod(_enclosingMethod_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AMethodScopeCommand(
            cloneNode(this._enclosingMethod_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodScopeCommand(this);
    }

    public TEnclosingMethod getEnclosingMethod()
    {
        return this._enclosingMethod_;
    }

    public void setEnclosingMethod(TEnclosingMethod node)
    {
        if(this._enclosingMethod_ != null)
        {
            this._enclosingMethod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enclosingMethod_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._enclosingMethod_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._enclosingMethod_ == child)
        {
            this._enclosingMethod_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._enclosingMethod_ == oldChild)
        {
            setEnclosingMethod((TEnclosingMethod) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
