/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AModuloFactExpr extends PFactExpr
{
    private PFactExpr _multDivModExprSrc_;
    private TModulo _modulo_;
    private PUnaryExpr _unitaryTarget_;

    public AModuloFactExpr()
    {
        // Constructor
    }

    public AModuloFactExpr(
        @SuppressWarnings("hiding") PFactExpr _multDivModExprSrc_,
        @SuppressWarnings("hiding") TModulo _modulo_,
        @SuppressWarnings("hiding") PUnaryExpr _unitaryTarget_)
    {
        // Constructor
        setMultDivModExprSrc(_multDivModExprSrc_);

        setModulo(_modulo_);

        setUnitaryTarget(_unitaryTarget_);

    }

    @Override
    public Object clone()
    {
        return new AModuloFactExpr(
            cloneNode(this._multDivModExprSrc_),
            cloneNode(this._modulo_),
            cloneNode(this._unitaryTarget_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModuloFactExpr(this);
    }

    public PFactExpr getMultDivModExprSrc()
    {
        return this._multDivModExprSrc_;
    }

    public void setMultDivModExprSrc(PFactExpr node)
    {
        if(this._multDivModExprSrc_ != null)
        {
            this._multDivModExprSrc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multDivModExprSrc_ = node;
    }

    public TModulo getModulo()
    {
        return this._modulo_;
    }

    public void setModulo(TModulo node)
    {
        if(this._modulo_ != null)
        {
            this._modulo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._modulo_ = node;
    }

    public PUnaryExpr getUnitaryTarget()
    {
        return this._unitaryTarget_;
    }

    public void setUnitaryTarget(PUnaryExpr node)
    {
        if(this._unitaryTarget_ != null)
        {
            this._unitaryTarget_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unitaryTarget_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multDivModExprSrc_)
            + toString(this._modulo_)
            + toString(this._unitaryTarget_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multDivModExprSrc_ == child)
        {
            this._multDivModExprSrc_ = null;
            return;
        }

        if(this._modulo_ == child)
        {
            this._modulo_ = null;
            return;
        }

        if(this._unitaryTarget_ == child)
        {
            this._unitaryTarget_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multDivModExprSrc_ == oldChild)
        {
            setMultDivModExprSrc((PFactExpr) newChild);
            return;
        }

        if(this._modulo_ == oldChild)
        {
            setModulo((TModulo) newChild);
            return;
        }

        if(this._unitaryTarget_ == oldChild)
        {
            setUnitaryTarget((PUnaryExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
