/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANotAnArithExpr extends PArithExpr
{
    private PFactExpr _factExpr_;

    public ANotAnArithExpr()
    {
        // Constructor
    }

    public ANotAnArithExpr(
        @SuppressWarnings("hiding") PFactExpr _factExpr_)
    {
        // Constructor
        setFactExpr(_factExpr_);

    }

    @Override
    public Object clone()
    {
        return new ANotAnArithExpr(
            cloneNode(this._factExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotAnArithExpr(this);
    }

    public PFactExpr getFactExpr()
    {
        return this._factExpr_;
    }

    public void setFactExpr(PFactExpr node)
    {
        if(this._factExpr_ != null)
        {
            this._factExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._factExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._factExpr_ == child)
        {
            this._factExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._factExpr_ == oldChild)
        {
            setFactExpr((PFactExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
