/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANotAComparisonExpr extends PComparisonExpr
{
    private PArithExpr _arithExpr_;

    public ANotAComparisonExpr()
    {
        // Constructor
    }

    public ANotAComparisonExpr(
        @SuppressWarnings("hiding") PArithExpr _arithExpr_)
    {
        // Constructor
        setArithExpr(_arithExpr_);

    }

    @Override
    public Object clone()
    {
        return new ANotAComparisonExpr(
            cloneNode(this._arithExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotAComparisonExpr(this);
    }

    public PArithExpr getArithExpr()
    {
        return this._arithExpr_;
    }

    public void setArithExpr(PArithExpr node)
    {
        if(this._arithExpr_ != null)
        {
            this._arithExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arithExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arithExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arithExpr_ == child)
        {
            this._arithExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arithExpr_ == oldChild)
        {
            setArithExpr((PArithExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
