/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANotAnAndExpr extends PAndExpr
{
    private PEqualityExpr _equalityExpr_;

    public ANotAnAndExpr()
    {
        // Constructor
    }

    public ANotAnAndExpr(
        @SuppressWarnings("hiding") PEqualityExpr _equalityExpr_)
    {
        // Constructor
        setEqualityExpr(_equalityExpr_);

    }

    @Override
    public Object clone()
    {
        return new ANotAnAndExpr(
            cloneNode(this._equalityExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotAnAndExpr(this);
    }

    public PEqualityExpr getEqualityExpr()
    {
        return this._equalityExpr_;
    }

    public void setEqualityExpr(PEqualityExpr node)
    {
        if(this._equalityExpr_ != null)
        {
            this._equalityExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalityExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equalityExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equalityExpr_ == child)
        {
            this._equalityExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equalityExpr_ == oldChild)
        {
            setEqualityExpr((PEqualityExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
