/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANotUnaryExpr extends PUnaryExpr
{
    private TNot _not_;
    private PUnaryExpr _unaryExpr_;

    public ANotUnaryExpr()
    {
        // Constructor
    }

    public ANotUnaryExpr(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PUnaryExpr _unaryExpr_)
    {
        // Constructor
        setNot(_not_);

        setUnaryExpr(_unaryExpr_);

    }

    @Override
    public Object clone()
    {
        return new ANotUnaryExpr(
            cloneNode(this._not_),
            cloneNode(this._unaryExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotUnaryExpr(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PUnaryExpr getUnaryExpr()
    {
        return this._unaryExpr_;
    }

    public void setUnaryExpr(PUnaryExpr node)
    {
        if(this._unaryExpr_ != null)
        {
            this._unaryExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._unaryExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._unaryExpr_ == child)
        {
            this._unaryExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._unaryExpr_ == oldChild)
        {
            setUnaryExpr((PUnaryExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
