/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOrExpr extends PExpr
{
    private PExpr _expr_;
    private TOr _or_;
    private PAndExpr _andExpr_;

    public AOrExpr()
    {
        // Constructor
    }

    public AOrExpr(
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") TOr _or_,
        @SuppressWarnings("hiding") PAndExpr _andExpr_)
    {
        // Constructor
        setExpr(_expr_);

        setOr(_or_);

        setAndExpr(_andExpr_);

    }

    @Override
    public Object clone()
    {
        return new AOrExpr(
            cloneNode(this._expr_),
            cloneNode(this._or_),
            cloneNode(this._andExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrExpr(this);
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public TOr getOr()
    {
        return this._or_;
    }

    public void setOr(TOr node)
    {
        if(this._or_ != null)
        {
            this._or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._or_ = node;
    }

    public PAndExpr getAndExpr()
    {
        return this._andExpr_;
    }

    public void setAndExpr(PAndExpr node)
    {
        if(this._andExpr_ != null)
        {
            this._andExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._andExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._or_)
            + toString(this._andExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._or_ == child)
        {
            this._or_ = null;
            return;
        }

        if(this._andExpr_ == child)
        {
            this._andExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(this._andExpr_ == oldChild)
        {
            setAndExpr((PAndExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
