/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class APlusUnaryExpr extends PUnaryExpr
{
    private TPlus _plus_;
    private PUnaryExpr _unaryExpr_;

    public APlusUnaryExpr()
    {
        // Constructor
    }

    public APlusUnaryExpr(
        @SuppressWarnings("hiding") TPlus _plus_,
        @SuppressWarnings("hiding") PUnaryExpr _unaryExpr_)
    {
        // Constructor
        setPlus(_plus_);

        setUnaryExpr(_unaryExpr_);

    }

    @Override
    public Object clone()
    {
        return new APlusUnaryExpr(
            cloneNode(this._plus_),
            cloneNode(this._unaryExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusUnaryExpr(this);
    }

    public TPlus getPlus()
    {
        return this._plus_;
    }

    public void setPlus(TPlus node)
    {
        if(this._plus_ != null)
        {
            this._plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PUnaryExpr getUnaryExpr()
    {
        return this._unaryExpr_;
    }

    public void setUnaryExpr(PUnaryExpr node)
    {
        if(this._unaryExpr_ != null)
        {
            this._unaryExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plus_)
            + toString(this._unaryExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plus_ == child)
        {
            this._plus_ = null;
            return;
        }

        if(this._unaryExpr_ == child)
        {
            this._unaryExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(this._unaryExpr_ == oldChild)
        {
            setUnaryExpr((PUnaryExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
