/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AStmts extends PStmts
{
    private PGenericStmt _genericStmt_;

    public AStmts()
    {
        // Constructor
    }

    public AStmts(
        @SuppressWarnings("hiding") PGenericStmt _genericStmt_)
    {
        // Constructor
        setGenericStmt(_genericStmt_);

    }

    @Override
    public Object clone()
    {
        return new AStmts(
            cloneNode(this._genericStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStmts(this);
    }

    public PGenericStmt getGenericStmt()
    {
        return this._genericStmt_;
    }

    public void setGenericStmt(PGenericStmt node)
    {
        if(this._genericStmt_ != null)
        {
            this._genericStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._genericStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._genericStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._genericStmt_ == child)
        {
            this._genericStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._genericStmt_ == oldChild)
        {
            setGenericStmt((PGenericStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
