/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TEnclosingMethod extends Token
{
    public TEnclosingMethod()
    {
        super.setText("enclosing_method");
    }

    public TEnclosingMethod(int line, int pos)
    {
        super.setText("enclosing_method");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEnclosingMethod(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEnclosingMethod(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEnclosingMethod text.");
    }
}
