/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TEndScope extends Token
{
    public TEndScope()
    {
        super.setText("end_scope");
    }

    public TEndScope(int line, int pos)
    {
        super.setText("end_scope");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEndScope(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEndScope(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEndScope text.");
    }
}
