/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TLookup2 extends Token
{
    public TLookup2()
    {
        super.setText("lookup2");
    }

    public TLookup2(int line, int pos)
    {
        super.setText("lookup2");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLookup2(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLookup2(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLookup2 text.");
    }
}
