/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TLookup1 extends Token
{
    public TLookup1()
    {
        super.setText("lookup1");
    }

    public TLookup1(int line, int pos)
    {
        super.setText("lookup1");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLookup1(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLookup1(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLookup1 text.");
    }
}
