/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TMethod extends Token
{
    public TMethod()
    {
        super.setText("method");
    }

    public TMethod(int line, int pos)
    {
        super.setText("method");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMethod(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMethod(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMethod text.");
    }
}
