/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TNewScope extends Token
{
    public TNewScope()
    {
        super.setText("new_scope");
    }

    public TNewScope(int line, int pos)
    {
        super.setText("new_scope");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNewScope(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNewScope(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNewScope text.");
    }
}
