/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TPrintSymtab extends Token
{
    public TPrintSymtab()
    {
        super.setText("print_symtab");
    }

    public TPrintSymtab(int line, int pos)
    {
        super.setText("print_symtab");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPrintSymtab(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPrintSymtab(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPrintSymtab text.");
    }
}
